// <auto-generated />
using System;
using FidelityCard.Srv.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FidelityCard.Srv.Data.Migrations
{
    [DbContext(typeof(FidelityCardDbContext))]
    partial class FidelityCardDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FidelityCard.Lib.Models.Fidelity", b =>
                {
                    b.Property<int>("IdFidelity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFidelity"));

                    b.Property<string>("Cap")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("CdFidelity")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Cellulare")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Cognome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("DataNascita")
                        .IsRequired()
                        .HasColumnType("smalldatetime");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Indirizzo")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Localita")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Nazione")
                        .HasMaxLength(2)
                        .HasColumnType("char(2)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Provincia")
                        .HasMaxLength(2)
                        .HasColumnType("char(2)");

                    b.Property<string>("Sesso")
                        .HasMaxLength(1)
                        .HasColumnType("char(1)");

                    b.Property<string>("Store")
                        .IsRequired()
                        .HasColumnType("varchar(6)")
                        .HasColumnName("CdNe");

                    b.HasKey("IdFidelity");

                    b.HasIndex("CdFidelity")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Fidelity");
                });
#pragma warning restore 612, 618
        }
    }
}
